### ISSUE TITLE
index.js anti-pattern

### ISSUE THREAD

**Issue by justinrlle** [ShinGecko/neKo-Api#5]
I think we should avoid the use of `index.js` files for controllers, and middlewares, and models.

When you need the controller of the users, we now do
```javascript
const controllers = require('./path/to/controllers')
controllers.users.auth(...)
```

But I think it would be clearer in all the way to do:
```javascript
const users = require('./path/to/controllers/users') // or require('./path/to/controllers/users.js')
users.auth(...)
```

We should keep the index.js in case we need to import a lot of controllers, but if we separate things correctly, it shouldn't happen.

In opposition, we should keep the index.js of the routes because the design is different.

So, @Shenrak, your take on this one?

**Comment by Shenrak** [comment]
Yeah I follow you on this one, in fact I designed it that way from habit.
